### PR TITLE
Release 0.16.0

### PR DESCRIPTION
**Pull request by jakirkham**
`````` rst
What's new in version 0.16.0 (2016-10-27)
==========================================

This release removes the ``configparser`` package as an alias for
``ConfigParser`` on Py2 to improve compatibility with Lukasz Langa's
backported `configparser <https://pypi.python.org/configparser>`_ package.
Previously ``python-future`` and the ``configparser`` backport clashed,
causing various compatibility issues. (Issues #118, #181)

If your code previously relied on ``configparser`` being supplied by
``python-future``, the recommended upgrade path is to run ``pip install
configparser`` or add ``configparser`` to your ``requirements.txt`` file.

Note that, if you are upgrading ``future`` with ``pip``, you may need to
uninstall the old version of future or manually remove the
``site-packages/future-0.15.2-py2.7.egg`` folder for this change to take
effect on your system.

This releases also fixes these bugs:

- Fix ``newbytes`` constructor bug. (Issue #163)
- Fix semantics of ``bool()`` with ``newobject``. (Issue #211)
- Fix ``standard_library.install_aliases()`` on PyPy. (Issue #205)
- Fix assertRaises for ``pow`` and ``compile``` on Python 3.5. (Issue #183)
- Fix return argument of ``future.utils.ensure_new_type`` if conversion to
  new type does not exist. (Issue #185)
- Add missing ``cmp_to_key`` for Py2.6. (Issue #189)
- Allow the ``old_div`` fixer to be disabled. (Issue #190)
- Improve compatibility with Google App Engine. (Issue #231)
- Add some missing imports to the ``tkinter`` and ``tkinter.filedialog``
  package namespaces. (Issues #212 and #233)
- More complete implementation of ``raise_from`` on PY3. (Issues #141,
  #213 and #235, fix provided by Varriount)
``````

xref: http://python-future.org/whatsnew.html#what-s-new-in-version-0-16-0-2016-10-27

### CODE REVIEW

**Comment by jakirkham** [comment]
Also adds myself as a maintainer by including PR ( https://github.com/conda-forge/future-feedstock/pull/3 ).

**Comment by jakirkham** [comment]
Needs some cleanup before we proceed. Most notably the PyPI URLs have been changed. Please see PR ( https://github.com/conda-forge/future-feedstock/pull/5 ) for details.

**Comment by mmysinger** [comment]
I thought the PyPI warehouse instance was still only a pre-release, should you really switch to those urls?

**Comment by jakirkham** [comment]
Yes, otherwise with newer package uploads we get horrible long URLs with some sort of version dependent hash included. Please try copying the URL from PyPI from [0.16.0](https://pypi.python.org/pypi/future/0.16.0) to see what I mean.

For more background, please read this issue ( https://github.com/conda-forge/staged-recipes/issues/481 ). Also this issue ( https://bitbucket.org/pypa/pypi/issues/438 ) is particularly relevant. In particular, this [comment](https://bitbucket.org/pypa/pypi/issues/438/backwards-compatible-un-hashed-package#comment-27606213) where the `pypi.io` URLs were offered up as the solution.

**Comment by jakirkham** [comment]
Went ahead and merged this as it had been sitting for a while and hadn't heard back from you in a while, @mmysinger. Hope that is ok. If there are concerns you have with these changes, please let me know and we can discuss what changes are needed.

**Pull request merged**
